# Generated by Django 2.1.2 on 2020-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='duration',
            new_name='operator',
        ),
        migrations.AlterField(
            model_name='assets',
            name='process',
            field=models.CharField(max_length=255),
        ),
    ]
