# Generated by Django 2.1.2 on 2020-03-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200316_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DataInputs',
        ),
        migrations.RemoveField(
            model_name='report',
            name='record',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='process',
            new_name='processor',
        ),
        migrations.AddField(
            model_name='process',
            name='acting_as',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='subjectsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Assets'),
        ),
        migrations.AddField(
            model_name='subjectsource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DataSubject'),
        ),
    ]
